spring.application.name=Mibodega
spring.main.banner-mode=off
spring.thymeleaf.cache=false
# Esto le dice a Spring Boot que no cargue la configuraci\u00f3n autom\u00e1tica de JPA, evitando errores por falta de base de datos.
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,\
#org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

spring.datasource.url=jdbc:mysql://localhost:3306/mibodega_bd_2?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa-database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate

# Usuario para pruebas
#spring.security.user.name=usuario@mibodega.com
#spring.security.user.password={noop}123

# Llave constante de jwt
jwt.secret=EstaEsUnaLLaveSecretaParaLaAplicacionMiBodega

logging.level.org.springframework.security=DEBUG
logging.level.utp.mdw.mibodega.configuracion=DEBUG
